### ISSUE TITLE
Blue is not Detecting

### ISSUE THREAD

**Issue by tombuttler12** [mitre/gameboard#13]
When I run Gameboard, the blue side never catches anything that the red side is doing. The only time there is ever anything caught is when I use batch planner on the blue side operation. The only thing that is being caught however, is the netcat I'm running which I understand is necessary to run a blue operation. 

What am I doing wrong?

Thank you.

**Comment by wbooth** [comment]
Hi @tombuttler12 are you deploying a blue agent on each host? Also have you checked the 'Auto-collect' operation on the blue side?
