### ISSUE TITLE
blue operations need to have their links manually pinned to the corresponding red link. 

### ISSUE THREAD

**Issue by ghost** [mitre/gameboard#26]
> Any other blue operations need to have their links manually pinned to the corresponding red link.

Hello. I received this answer earlier from @garunagiri 
Please tell me how the user abilities of the defenders to me link to the red link. How can i do it manually ?

**Comment by garunagiri** [comment]
Hi Veslo. There is likely an upcoming change to this, but currently the way to pin a blue link to a red link is by clicking on the blue link's star icon, entering the red link's Process ID within the Pinned PID field, and clicking save at the bottom.
![image](https://user-images.githubusercontent.com/57109409/107649778-ccd83300-6c4b-11eb-9604-29167a7fdb4f.png)

You can easily find a red link's PID also within the GameBoard plugin.
![image](https://user-images.githubusercontent.com/57109409/107649649-ab774700-6c4b-11eb-83f9-8d17c7506c08.png)

**Comment by ghost** [comment]
@garunagiri 
Thanks for your reply. This is certainly not very convenient, it turns out that you need to connect every ability from the red team with every ability of the blue team. Do I understand you correctly?

**Comment by garunagiri** [comment]
Yes. As of now, only the Auto-collect operation has the capability to be automatically linked with red abilities, as that is the only operation that has information on that kind of link. No other operation does, so such a link would have to be manually done.

**Comment by ghost** [comment]
@garunagiri Thank you for explaining my questions to me)

**Comment by garunagiri** [comment]
Happy to help!
